/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#F5AFAF',
        'secondary-container': '#F9DFDF',
        'on-primary-container': '#3D1515',
        'secondary-fixed': '#F9DFDF',
        'on-secondary-fixed-variant': '#6B3535',
        'surface-container-low': '#FBEFEF',
        'surface-dim': '#F5AFAF',
        'error': '#ba1a1a',
        'surface-variant': '#F9DFDF',
        'background': '#FCF8F8',
        'tertiary-fixed-dim': '#F5AFAF',
        'surface-container': '#F9DFDF',
        'inverse-on-surface': '#FCF8F8',
        'surface': '#FCF8F8',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#F5AFAF',
        'secondary': '#8B5353',
        'on-primary': '#ffffff',
        'outline-variant': '#F5AFAF',
        'tertiary-fixed': '#F9DFDF',
        'primary': '#C47B7B',
        'on-error': '#ffffff',
        'on-primary-fixed': '#2A0D0D',
        'on-primary-fixed-variant': '#6B3535',
        'inverse-surface': '#2A0D0D',
        'error-container': '#ffdad6',
        'primary-fixed': '#F9DFDF',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#2A0D0D',
        'on-surface': '#2A0D0D',
        'surface-container-high': '#F9DFDF',
        'on-tertiary-fixed-variant': '#8B4444',
        'surface-container-lowest': '#FCF8F8',
        'surface-bright': '#FCF8F8',
        'on-tertiary-container': '#3D1515',
        'on-tertiary-fixed': '#2A0D0D',
        'on-surface-variant': '#6B3535',
        'surface-container-highest': '#F5AFAF',
        'on-background': '#2A0D0D',
        'surface-tint': '#C47B7B',
        'tertiary-container': '#F5AFAF',
        'outline': '#C47B7B',
        'primary-container': '#F9DFDF',
        'secondary-fixed-dim': '#F5AFAF',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#6B3535',
        'tertiary': '#B56666',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        unit: '8px',
        'container-max': '1280px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        fraunces: ['var(--font-fraunces)', 'serif'],
        manrope: ['var(--font-manrope)', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
