/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#ffb1c1',
        'secondary-container': '#efdee0',
        'on-primary-container': '#5c2634',
        'secondary-fixed': '#efdee0',
        'on-secondary-fixed-variant': '#4f4446',
        'surface-container-low': '#fbf2ec',
        'surface-dim': '#e1d8d3',
        'error': '#ba1a1a',
        'surface-variant': '#eae1db',
        'background': '#fff8f4',
        'tertiary-fixed-dim': '#ffb2bf',
        'surface-container': '#f5ece6',
        'inverse-on-surface': '#f8efe9',
        'surface': '#fff8f4',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#ffb1c1',
        'secondary': '#675b5d',
        'on-primary': '#ffffff',
        'outline-variant': '#d6c1c4',
        'tertiary-fixed': '#ffd9de',
        'primary': '#8a4c5a',
        'on-error': '#ffffff',
        'on-primary-fixed': '#380919',
        'on-primary-fixed-variant': '#6e3445',
        'inverse-surface': '#34302c',
        'error-container': '#ffdad6',
        'primary-fixed': '#ffd9df',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#22191b',
        'on-surface': '#1f1b17',
        'surface-container-high': '#efe7e1',
        'on-tertiary-fixed-variant': '#80243e',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#fff8f4',
        'on-tertiary-container': '#6c132f',
        'on-tertiary-fixed': '#3f0016',
        'on-surface-variant': '#524345',
        'surface-container-highest': '#eae1db',
        'on-background': '#1f1b17',
        'surface-tint': '#8a4c5a',
        'tertiary-container': '#f17c96',
        'outline': '#847375',
        'primary-container': '#d68c9c',
        'secondary-fixed-dim': '#d3c3c5',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#6e6163',
        'tertiary': '#9f3c55',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        unit: '8px',
        'container-max': '1280px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        fraunces: ['var(--font-fraunces)', 'serif'],
        manrope: ['var(--font-manrope)', 'sans-serif'],
        'headline-lg': ['var(--font-eb-garamond)', 'serif'],
        'headline-md': ['var(--font-eb-garamond)', 'serif'],
        'headline-xl': ['var(--font-eb-garamond)', 'serif'],
        'body-md': ['var(--font-hanken-grotesk)', 'sans-serif'],
        'body-lg': ['var(--font-hanken-grotesk)', 'sans-serif'],
        'label-caps': ['var(--font-hanken-grotesk)', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
