import express, { type Request, type Response } from 'express'
import cors from 'cors'
import helmet from 'helmet'
import rateLimit from 'express-rate-limit'
import morgan from 'morgan'
import multer from 'multer'
import sharp from 'sharp'
import bcrypt from 'bcryptjs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { config } from './config.js'
import { supabase } from './supabase.js'
import { categorySchema, featuredSchema, passwordSchema, productSchema } from './schemas.js'
import { requireAdmin, signAdminToken } from './auth.js'

const app = express(); const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024, files: 10 }, fileFilter: (_req, file, callback) => callback(null, /^image\/(jpeg|png|webp|gif|avif)$/.test(file.mimetype)) })
app.use(helmet({ crossOriginResourcePolicy: false })); app.use(cors({ origin: (origin, callback) => callback(null, !origin || config.corsOrigins.includes(origin)), methods: ['GET', 'POST', 'PUT', 'DELETE'], allowedHeaders: ['Content-Type', 'Authorization'] })); app.use(morgan(config.nodeEnv === 'production' ? 'combined' : 'dev')); app.use(express.json({ limit: '1mb' })); app.use('/api', rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: 'draft-8', legacyHeaders: false }))
const parse = <T>(schema: { safeParse: (input: unknown) => { success: boolean; data?: T; error?: { flatten: () => unknown } } }, input: unknown, response: Response): T | undefined => { const result = schema.safeParse(input); if (!result.success) { response.status(400).json({ error: 'Invalid input', details: result.error?.flatten() }); return undefined }; return result.data }
const dbError = (response: Response, error: { message: string }) => response.status(500).json({ error: error.message })

app.get('/api/products', async (request, response) => { let query = supabase.from('products').select('*').order('created_at', { ascending: false }); if (typeof request.query.main_category === 'string') query = query.eq('main_category', request.query.main_category); const { data, error } = await query; return error ? dbError(response, error) : response.json(data) })
app.get('/api/products/:id', async (request, response) => { const { data, error } = await supabase.from('products').select('*').eq('id', Number(request.params.id)).maybeSingle(); if (error) return dbError(response, error); return data ? response.json(data) : response.status(404).json({ error: 'Not found' }) })
app.post('/api/products', requireAdmin, async (request, response) => { const input = parse(productSchema, request.body, response); if (!input) return; const { data, error } = await supabase.from('products').insert(input).select().single(); return error ? dbError(response, error) : response.status(201).json(data) })
app.put('/api/products/:id', requireAdmin, async (request, response) => { const input = parse(productSchema, request.body, response); if (!input) return; const { data, error } = await supabase.from('products').update(input).eq('id', Number(request.params.id)).select().maybeSingle(); if (error) return dbError(response, error); return data ? response.json(data) : response.status(404).json({ error: 'Not found' }) })
app.delete('/api/products/:id', requireAdmin, async (request, response) => { const { error } = await supabase.from('products').delete().eq('id', Number(request.params.id)); return error ? dbError(response, error) : response.json({ ok: true }) })

app.get('/api/categories', async (_request, response) => { const { data, error } = await supabase.from('categories').select('*').order('main_category').order('name'); return error ? dbError(response, error) : response.json(data) })
app.post('/api/categories', requireAdmin, async (request, response) => { const input = parse(categorySchema, request.body, response); if (!input) return; const { data, error } = await supabase.from('categories').upsert(input, { onConflict: 'slug' }).select().single(); return error ? dbError(response, error) : response.status(201).json(data) })
app.put('/api/categories/:id', requireAdmin, async (request, response) => { const input = parse(categorySchema, request.body, response); if (!input) return; const { data, error } = await supabase.from('categories').update(input).eq('id', Number(request.params.id)).select().maybeSingle(); if (error) return dbError(response, error); return data ? response.json(data) : response.status(404).json({ error: 'Not found' }) })
app.delete('/api/categories/:id', requireAdmin, async (request, response) => { const { error } = await supabase.from('categories').delete().eq('id', Number(request.params.id)); return error ? dbError(response, error) : response.json({ ok: true }) })

app.get('/api/featured-products', async (_request, response) => { const { data: setting, error } = await supabase.from('store_settings').select('value').eq('key', 'featured_product_ids').maybeSingle(); if (error) return dbError(response, error); const productIds = Array.isArray(setting?.value) ? setting.value.map(Number) : [1, 7, 13, 18]; const { data: all, error: productsError } = await supabase.from('products').select('*'); if (productsError) return dbError(response, productsError); const map = new Map((all ?? []).map(product => [product.id, product])); return response.json({ productIds, items: productIds.map(id => map.get(id)).filter(Boolean) }) })
app.put('/api/featured-products', requireAdmin, async (request, response) => { const input = parse(featuredSchema, request.body, response); if (!input) return; const { count, error: countError } = await supabase.from('products').select('*', { count: 'exact', head: true }).in('id', input.productIds); if (countError) return dbError(response, countError); if (count !== 4) return response.status(400).json({ error: 'One or more selected products do not exist' }); const { error } = await supabase.from('store_settings').upsert({ key: 'featured_product_ids', value: input.productIds }); return error ? dbError(response, error) : response.json({ productIds: input.productIds }) })

app.get('/api/auth/me', requireAdmin, (_request, response) => response.json({ isLoggedIn: true }))
app.post('/api/auth/setup', async (request, response) => { const input = parse(passwordSchema, request.body, response); if (!input) return; const { data, error } = await supabase.from('admin_settings').select('value').eq('key', 'admin_password_hash').maybeSingle(); if (error) return dbError(response, error); if (data) return response.status(409).json({ error: 'Admin already configured' }); const hash = await bcrypt.hash(input.password, 12); const { error: writeError } = await supabase.from('admin_settings').insert({ key: 'admin_password_hash', value: hash }); return writeError ? dbError(response, writeError) : response.json({ token: signAdminToken() }) })
app.post('/api/auth/login', async (request, response) => { const input = parse(passwordSchema, request.body, response); if (!input) return; const { data, error } = await supabase.from('admin_settings').select('value').eq('key', 'admin_password_hash').maybeSingle(); if (error) return dbError(response, error); if (!data) return response.status(409).json({ error: 'Admin not configured' }); return (await bcrypt.compare(input.password, data.value)) ? response.json({ token: signAdminToken() }) : response.status(401).json({ error: 'Invalid password' }) })
app.post('/api/auth/logout', requireAdmin, (_request, response) => response.json({ ok: true }))
app.post('/api/upload', requireAdmin, upload.single('file'), async (request, response) => { if (!request.file) return response.status(400).json({ error: 'An image file is required' }); try { const webp = await sharp(request.file.buffer).rotate().webp({ quality: 85 }).toBuffer(); const name = `${Date.now()}-${crypto.randomUUID()}.webp`; const { error } = await supabase.storage.from(config.storageBucket).upload(name, webp, { contentType: 'image/webp', upsert: false }); if (error) return dbError(response, error); const { data } = supabase.storage.from(config.storageBucket).getPublicUrl(name); return response.status(201).json({ url: data.publicUrl }) } catch { return response.status(400).json({ error: 'Unable to process image' }) } })

if (config.nodeEnv === 'production') { const directory = path.dirname(fileURLToPath(import.meta.url)); app.use(express.static(path.resolve(directory, '../dist'))); app.get('*', (_request, response) => response.sendFile(path.resolve(directory, '../dist/index.html'))) }
app.listen(config.port, () => console.log(`Maison Rose API listening on :${config.port}`))
