import { Link } from 'wouter'
import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import { ParallaxImage } from '../components/ParallaxImage'
import { ProductCard } from '../components/ProductCard'
import { api } from '../lib/api'
import type { FeaturedResponse, Product, SiteImages } from '../types'

const HERO_IMAGE = 'https://slidesdocs.com/background/cute-little-flowers-blue-sky-and-white-clouds-simple-nature-powerpoint-background_74e3443a74'
const IMG_BAGS = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvJ4D_HSb0qDFIU-ANm55iElbMp2HBTv2Cx5QlulNHUORFHJZxHFJKsCeS8EOjyHxsHrY8mNUXNicw7WG_5Um6bLg8fVKnz3LKJAV4OOjye13wlcFDrwcur8WGyJg_C2jOJIckgU9DWJIu-M37eNKpNLf7osS55oRkiU-2Bz5l9AyiK3P8vw3P4At1d4TRs6oMioqVvpbCb3HjnLsNj0ykk5RrAoxs2yh0lAUmjBt4-PYtLjTqb4Fn'
const IMG_JEWELRY = 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0Bikepsu2EEQsFjPBGxYB0yqYAzCYhozNmzkAXhgcK87_py-tnVLO-uUB3LgaQ3SOPXMCP5VcotntBKh-NZWTlYe2HkQoGLMjPUzurQNwyZM3G6iG_EDDJLQgCgkGq8bbZEf3378Ko3ZWxOSiIO5R09vways9cBdmaU8jW8Ce088RHTzVpeIzVt5h14icSwApPkBj6CiFFodF27-TJLJo7nOdvAKHVAMtK2TZemsboMvc83tEvLVL'
const IMG_SCARVES = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCfxvE5bZlw0oLwwQlTfTWvTAwJ3FC1gLfQEesaLaxDgiJouHsHqM4XsN6pGScxLYqm-0fN7rLAWrOAU1YFHcp7H-nM1YXuF9KrIw4xQ4rhzbnpZC7BdKU6JMcow4BIQVn9UXGxdXbV6e2JeVV2iAslJGDDkBDxpe2pKNOY04MCl1PopUTG4CEHM82_L6foEN5nsjl1cOmrGtcW5yrLGYN0wDEbsehiLgh-0ZTGRU--hrY_RmxYOHLd'
const IMG_HOME = HERO_IMAGE
const fallback: Product[] = [{ id: 1, name: 'La Calla Tote', subtitle: '', description: '', price: 2400, main_category: 'bags', category: 'tote', status: 'available', badge: 'New', quantity: 1, images: [IMG_BAGS], bg_class: 'bg-surface-container-high', created_at: '', updated_at: '' }, { id: 7, name: "Fil d'Or Chain", subtitle: '', description: '', price: 890, main_category: 'jewelry', category: 'necklace', status: 'available', badge: 'New', quantity: 1, images: [IMG_JEWELRY], bg_class: 'bg-surface-container', created_at: '', updated_at: '' }, { id: 13, name: 'Heritage Silk Scarf', subtitle: '', description: '', price: 620, main_category: 'accessories', category: 'scarf', status: 'available', badge: 'New', quantity: 1, images: [IMG_SCARVES], bg_class: 'bg-surface-container-highest', created_at: '', updated_at: '' }, { id: 18, name: 'Tourbillon No. 1', subtitle: '', description: '', price: 18500, main_category: 'accessories', category: 'watch', status: 'available', badge: 'Limited', quantity: 1, images: [HERO_IMAGE], bg_class: 'bg-surface-container-high', created_at: '', updated_at: '' }]

const faqs = [
  { q: 'What kind of products do you sell?', a: 'We offer beauty and makeup products, accessories, home essentials, bags, jewellery, and more. Our collection is regularly updated with new items.' },
  { q: 'Why are your prices more affordable?', a: 'Many items come from PR packages and brand collaborations, allowing us to offer them at lower prices than traditional retail stores.' },
  { q: 'Are the products original and authentic?', a: 'Yes. Our products come from trusted sources and brand collaborations. Product details and condition are clearly mentioned before purchase.' },
  { q: 'How can I place an order?', a: 'Choose a product, add it to your cart, and complete your order through our website. Contact us if you need any help.' },
]

  export function HomePage() {
  const [open, setOpen] = useState<number | null>(0); const [heroLoaded, setHeroLoaded] = useState(false); const { data } = useQuery({ queryKey: ['featured-products'], queryFn: () => api<FeaturedResponse>('/featured-products'), staleTime: 60_000 }); const { data: siteImages } = useQuery({ queryKey: ['site-images'], queryFn: () => api<SiteImages>('/site-images') }); const featured = data?.items?.length ? data.items : fallback; const heroImage = heroLoaded ? siteImages?.hero || HERO_IMAGE : HERO_IMAGE; const heroImageMobile = heroLoaded ? siteImages?.hero_mobile || siteImages?.hero || HERO_IMAGE : HERO_IMAGE
  useEffect(() => { if (!siteImages) return; const url = siteImages.hero_mobile || siteImages.hero || HERO_IMAGE; const image = new Image(); image.onload = () => setHeroLoaded(true); image.onerror = () => setHeroLoaded(true); if (image.complete && image.naturalWidth > 0) { setHeroLoaded(true); return } image.src = url }, [siteImages])
  const categoryImage = { bags: siteImages?.bags || IMG_BAGS, jewelry: siteImages?.jewelry || IMG_JEWELRY, accessories: siteImages?.accessories || IMG_SCARVES, home: siteImages?.home || IMG_HOME }
  const editorial = [{ eyebrow: 'Bags', title: 'The Bag Edit', body: 'From everyday totes to cute statement bags, discover pieces that instantly elevate your outfit — whether you’re heading to university, work, coffee or a day out.', href: '/bags', button: 'Shop Bags', image: categoryImage.bags, reverse: false, bone: true }, { eyebrow: 'Jewelry', title: 'The Jewelry Edit', body: 'Dainty, feminine and effortlessly wearable — discover jewellery pieces that add just the right amount of sparkle to your everyday style.', href: '/jewelry', button: 'Shop Jewelry', image: categoryImage.jewelry, reverse: true, bone: false }, { eyebrow: 'Accessories', title: 'The Accessory Edit', body: 'All the little things you didn’t know you needed. A fun mix of cute, useful & aesthetic finds — from everyday essentials to those little pieces that instantly make life a bit prettier.', href: '/accessories', button: 'Shop Accessories', image: categoryImage.accessories, reverse: false, bone: true }, { eyebrow: 'Home', title: 'The Home Edit', body: 'Little things that make home feel even prettier. Discover a mix of cute, practical & aesthetic home essentials — from everyday must-haves to those little finds that make your space feel more you.', href: '/home', button: 'Shop Home', image: categoryImage.home, reverse: true, bone: false }]
  return <main><section className="relative w-full h-screen min-h-[640px] flex items-center justify-start overflow-hidden bg-surface-container"><div className="absolute inset-0 z-0"><img src={heroImageMobile} alt="The Heritage Collection" className="w-full h-full object-cover object-center opacity-80 ken-burns md:hidden" loading="eager" fetchPriority="high" decoding="sync" /><img src={heroImage} alt="The Heritage Collection" className="hidden w-full h-full object-cover object-center opacity-80 ken-burns md:block" loading="eager" fetchPriority="high" decoding="sync" /><div className="absolute inset-0 bg-gradient-to-r from-white/70 via-white/20 to-transparent" /></div><div className="relative z-10 w-full max-w-7xl mx-auto px-5 md:px-margin-desktop grid grid-cols-4 md:grid-cols-12 gap-6"><div className="col-span-4 md:col-span-7 flex flex-col justify-center items-start"><p className="font-manrope text-[11px] uppercase tracking-[.18em] text-on-primary-container mb-7">FROM MY PR BOX TO YOUR WISHLIST</p><motion.h1 initial={false} className="font-fraunces text-4xl md:text-5xl lg:text-6xl text-on-background mb-7 max-w-xl leading-[1.0]">Pretty Picks,<br />Better Prices.</motion.h1><p className="font-manrope text-[13px] md:text-sm text-on-surface-variant max-w-sm leading-[1.75] tracking-wide">This is Fatima Saif and here’s a little space where I share my PR finds with you at cute, affordable prices, often lower than the original website price. Just a little piece of my creator world, now yours. ♡</p></div></div><div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 scroll-indicator"><span className="font-manrope text-[10px] uppercase tracking-widest text-on-surface-variant/60">Scroll</span><span className="material-symbols-outlined text-on-surface-variant/60 text-[18px]">arrow_downward</span></div></section>
  <section className="py-24 md:py-36 px-5 md:px-margin-desktop bg-surface-container-low"><div className="max-w-container-max mx-auto"><div className="flex flex-col md:flex-row md:items-end justify-between mb-14 gap-6"><div><div className="flex items-center gap-3 mb-4"><div className="quote-rule" /><p className="font-manrope text-xs uppercase tracking-widest text-on-surface-variant">Curated Selection</p></div><h2 className="font-fraunces text-4xl md:text-5xl text-on-background leading-tight">Featured Products</h2></div><Link href="/bags" className="font-manrope text-xs uppercase tracking-widest text-on-surface-variant hover:text-primary border-b border-outline-variant hover:border-primary pb-1 self-start md:self-auto whitespace-nowrap">View All →</Link></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-6">{featured.map((product, index) => <ProductCard key={product.id} product={product} delay={index * 80} />)}</div></div></section>
  {editorial.map(item => <section key={item.title} className={`py-24 md:py-36 px-5 md:px-margin-desktop overflow-hidden ${item.bone ? 'bg-bone' : 'bg-surface'}`}><div className="max-w-container-max mx-auto grid grid-cols-1 md:grid-cols-12 gap-12 md:gap-24 items-center"><div className={`md:col-span-7 ${item.reverse ? 'order-2' : 'order-2 md:order-1'} w-full`}><ParallaxImage image={item.image} className="glint-container w-full" /><div className="mt-6 md:hidden"><Link href={item.href} className="inline-flex items-center h-[52px] px-8 bg-tertiary text-on-tertiary font-manrope text-xs uppercase tracking-widest border border-tertiary hover:bg-primary hover:text-on-primary transition-colors">{item.button}</Link></div></div><div className={`md:col-span-5 ${item.reverse ? 'order-1 md:items-end md:text-right' : 'order-1 md:order-2'} flex flex-col items-start`}><div className={`flex items-center gap-3 mb-6 ${item.reverse ? 'md:flex-row-reverse' : ''}`}><div className="quote-rule" /><p className="font-manrope text-xs uppercase tracking-widest text-on-surface-variant">{item.eyebrow}</p></div><h2 className="font-fraunces text-4xl md:text-5xl text-on-background mb-6 leading-tight">{item.title}</h2><p className="font-manrope text-base md:text-lg text-on-surface-variant mb-10 leading-relaxed">{item.body}</p><Link href={item.href} className="hidden md:inline-flex items-center h-[52px] px-8 bg-tertiary text-on-tertiary font-manrope text-xs uppercase tracking-widest border border-tertiary hover:bg-primary hover:text-on-primary transition-colors">{item.button}</Link></div></div></section>)}<section className="py-24 md:py-36 px-5 md:px-margin-desktop bg-surface-container-lowest"><div className="max-w-3xl mx-auto"><p className="font-manrope text-[11px] uppercase tracking-[.18em] text-on-surface-variant mb-4">FAQ</p><h2 className="font-fraunces text-4xl md:text-5xl text-on-background leading-tight mb-10">FAQs</h2><div>{faqs.map((item, index) => { const active = open === index; return (
  <div key={item.q} className="border-b border-outline-variant"><button onClick={() => setOpen(active ? null : index)} aria-expanded={active} aria-controls={`home-faq-${index}`} className="w-full flex items-center justify-between gap-6 py-6 text-left"><span className={`font-fraunces text-lg md:text-xl ${active ? 'text-primary' : 'text-on-background'}`}>{item.q}</span><span className={`material-symbols-outlined text-[22px] text-on-surface-variant transition-transform duration-300 ${active ? 'rotate-45' : ''}`}>add</span></button><div id={`home-faq-${index}`} className={`grid transition-all duration-300 ${active ? 'grid-rows-[1fr] opacity-100 pb-6' : 'grid-rows-[0fr] opacity-0'}`}><div className="overflow-hidden"><p className="font-manrope text-sm text-on-surface-variant leading-relaxed max-w-2xl">{item.a}</p></div></div></div>
) })}</div></div></section></main>
}
