import { Link } from 'wouter'
import { useQuery } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import { useCart } from '../context/CartContext'
import { api } from '../lib/api'
import type { FeaturedResponse, Product } from '../types'

const HERO_IMAGE = 'https://lh3.googleusercontent.com/aida-public/AB6AXuANMqbxmRClPeN4wqgJNK9lX_xh8qwucq78m6OK_9UjCrS0uVO6ZxxXLZ-v6mbv267Z3D_mT5hVU0eCwluNqnU7FlyFvsVE986l_Cewo03tbFtMbIfElwrIDNiDFojHXaRd_JgJHrIuF3Tv2xNqbbQnD64NIGkNk06hS4AOBwm3-KZ6ukm9iTlaWvWCAXNx3__Gbq_4XE5dNu2rNyCQDIHnM2McaKJuYlUU7Dr1P-PcZ7m6sGyeO6tQ'
const IMG_BAGS = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvJ4D_HSb0qDFIU-ANm55iElbMp2HBTv2Cx5QlulNHUORFHJZxHFJKsCeS8EOjyHxsHrY8mNUXNicw7WG_5Um6bLg8fVKnz3LKJAV4OOjye13wlcFDrwcur8WGyJg_C2jOJIckgU9DWJIu-M37eNKpNLf7osS55oRkiU-2Bz5l9AyiK3P8vw3P4At1d4TRs6oMioqVvpbCb3HjnLsNj0ykk5RrAoxs2yh0lAUmjBt4-PYtLjTqb4Fn'
const IMG_JEWELRY = 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0Bikepsu2EEQsFjPBGxYB0yqYAzCYhozNmzkAXhgcK87_py-tnVLO-uUB3LgaQ3SOPXMCP5VcotntBKh-NZWTlYe2HkQoGLMjPUzurQNwyZM3G6iG_EDDJLQgCgkGq8bbZEf3378Ko3ZWxOSiIO5R09vways9cBdmaU8jW8Ce088RHTzVpeIzVt5h14icSwApPkBj6CiFFodF27-TJLJo7nOdvAKHVAMtK2TZemsboMvc83tEvLVL'
const IMG_SCARVES = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCfxvE5bZlw0oLwwQlTfTWvTAwJ3FC1gLfQEesaLaxDgiJouHsHqM4XsN6pGScxLYqm-0fN7rLAWrOAU1YFHcp7H-nM1YXuF9KrIw4xQ4rhzbnpZC7BdKU6JMcow4BIQVn9UXGxdXbV6e2JeVV2iAslJGDDkBDxpe2pKNOY04MCl1PopUTG4CEHM82_L6foEN5nsjl1cOmrGtcW5yrLGYN0wDEbsehiLgh-0ZTGRU--hrY_RmxYOHLd'
const fallback: Product[] = [{ id: 1, name: 'La Calla Tote', subtitle: '', description: '', price: 2400, main_category: 'bags', category: 'tote', status: 'available', badge: 'New', quantity: 1, images: [IMG_BAGS], bg_class: 'bg-surface-container-high', created_at: '', updated_at: '' }, { id: 7, name: "Fil d'Or Chain", subtitle: '', description: '', price: 890, main_category: 'jewelry', category: 'necklace', status: 'available', badge: 'New', quantity: 1, images: [IMG_JEWELRY], bg_class: 'bg-surface-container', created_at: '', updated_at: '' }, { id: 13, name: 'Heritage Silk Scarf', subtitle: '', description: '', price: 620, main_category: 'accessories', category: 'scarf', status: 'available', badge: 'New', quantity: 1, images: [IMG_SCARVES], bg_class: 'bg-surface-container-highest', created_at: '', updated_at: '' }, { id: 18, name: 'Tourbillon No. 1', subtitle: '', description: '', price: 18500, main_category: 'accessories', category: 'watch', status: 'available', badge: 'Limited', quantity: 1, images: [HERO_IMAGE], bg_class: 'bg-surface-container-high', created_at: '', updated_at: '' }]

export function HomePage() {
  const { addToCart } = useCart(); const { data } = useQuery({ queryKey: ['featured-products'], queryFn: () => api<FeaturedResponse>('/featured-products'), staleTime: 60_000 }); const featured = data?.items?.length === 4 ? data.items : fallback
  const editorial = [{ eyebrow: 'The Edit', title: 'The Leather Edit', body: 'Sculptural silhouettes crafted from full-grain calfskin. A masterclass in quiet luxury, designed for the modern muse who commands attention without saying a word.', href: '/bags', button: 'Shop Bags', image: IMG_BAGS, reverse: false, bone: true }, { eyebrow: 'Fine Jewelry', title: 'The Jewelry Collection', body: 'Delicate chains, ethically sourced stones, and heirloom-quality craftsmanship. Adorn yourself in timeless radiance that captures the essence of Maison Rose.', href: '/jewelry', button: 'Shop Jewelry', image: IMG_JEWELRY, reverse: true, bone: false }, { eyebrow: 'Accessories', title: 'Timeless Accessories', body: 'Elevate the everyday. From silk scarves to meticulously engineered timepieces, discover the finishing touches that redefine elegance.', href: '/accessories', button: 'Shop Accessories', image: IMG_SCARVES, reverse: false, bone: true }]
  return <main><section className="relative w-full h-screen min-h-[640px] flex items-center justify-start overflow-hidden bg-ink-plum"><div className="absolute inset-0 z-0"><div className="w-full h-full bg-cover bg-center opacity-80 ken-burns" style={{ backgroundImage: `url('${HERO_IMAGE}')` }} /><div className="absolute inset-0 bg-gradient-to-r from-ink-plum/70 via-ink-plum/30 to-transparent" /></div><div className="relative z-10 w-full max-w-7xl mx-auto px-5 md:px-margin-desktop grid grid-cols-4 md:grid-cols-12 gap-6"><div className="col-span-4 md:col-span-7 flex flex-col justify-center items-start"><p className="font-manrope text-[11px] uppercase tracking-[.18em] text-primary-container mb-7">The Heritage Collection — 2025</p><motion.h1 initial={false} className="font-fraunces text-4xl md:text-5xl lg:text-6xl text-on-primary mb-7 max-w-xl leading-[1.0]">THE WEIGHT<br />OF TIME</motion.h1><p className="font-manrope text-[13px] md:text-sm text-on-primary/65 max-w-xs leading-[1.75] tracking-wide">Where precision mechanics meet undeniable artistry. Discover timepieces crafted for those who understand that true luxury cannot be rushed.</p></div></div><div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 scroll-indicator"><span className="font-manrope text-[10px] uppercase tracking-widest text-on-primary/50">Scroll</span><span className="material-symbols-outlined text-on-primary/50 text-[18px]">arrow_downward</span></div></section>
  <section className="py-24 md:py-36 px-5 md:px-margin-desktop bg-surface-container-low"><div className="max-w-container-max mx-auto"><div className="flex flex-col md:flex-row md:items-end justify-between mb-14 gap-6"><div><div className="flex items-center gap-3 mb-4"><div className="quote-rule" /><p className="font-manrope text-xs uppercase tracking-widest text-on-surface-variant">Curated Selection</p></div><h2 className="font-fraunces text-4xl md:text-5xl text-on-background leading-tight">Featured Products</h2></div><Link href="/bags" className="font-manrope text-xs uppercase tracking-widest text-on-surface-variant hover:text-primary border-b border-outline-variant hover:border-primary pb-1 self-start md:self-auto whitespace-nowrap">View All →</Link></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-6">{featured.map(product => <div key={product.id} className="product-card group cursor-pointer"><div className={`overflow-hidden mb-4 relative ${product.bg_class} aspect-[3/4]`}><div className="product-img w-full h-full bg-cover bg-center" style={{ backgroundImage: `url('${product.images[0] || ''}')` }} /><div className="absolute bottom-0 left-0 right-0 p-3"><button onClick={() => addToCart(product.name, product.price)} className="product-cta w-full h-10 bg-surface/90 backdrop-blur-sm text-on-surface font-manrope text-[10px] uppercase tracking-widest hover:bg-tertiary hover:text-on-tertiary">Add to Bag</button></div>{product.badge && <div className="absolute top-3 left-3"><span className={product.badge === 'New' ? 'px-2 py-1 bg-tertiary text-on-tertiary font-manrope text-[9px] uppercase tracking-widest' : 'px-2 py-1 bg-surface-container text-on-surface-variant font-manrope text-[9px] uppercase tracking-widest border border-outline-variant'}>{product.badge}</span></div>}</div><p className="font-manrope text-[10px] uppercase tracking-widest text-on-surface-variant mb-1">Maison Rose</p><p className="font-fraunces text-base md:text-lg text-on-background mb-1 leading-tight">{product.name}</p><p className="font-manrope text-sm text-on-surface-variant">€ {product.price.toLocaleString()}</p></div>)}</div></div></section>
  {editorial.map(item => <section key={item.title} className={`py-24 md:py-36 px-5 md:px-margin-desktop overflow-hidden ${item.bone ? 'bg-bone' : 'bg-surface'}`}><div className="max-w-container-max mx-auto grid grid-cols-1 md:grid-cols-12 gap-12 md:gap-24 items-center"><div className={`md:col-span-7 ${item.reverse ? 'order-2' : 'order-2 md:order-1'} glint-container h-[60vh] md:h-[80vh] w-full`}><div className="w-full h-full bg-cover bg-center parallax-bg" style={{ backgroundImage: `url('${item.image}')` }} /></div><div className={`md:col-span-5 ${item.reverse ? 'order-1 md:items-end md:text-right' : 'order-1 md:order-2'} flex flex-col items-start`}><div className={`flex items-center gap-3 mb-6 ${item.reverse ? 'md:flex-row-reverse' : ''}`}><div className="quote-rule" /><p className="font-manrope text-xs uppercase tracking-widest text-on-surface-variant">{item.eyebrow}</p></div><h2 className="font-fraunces text-4xl md:text-5xl text-on-background mb-6 leading-tight">{item.title}</h2><p className="font-manrope text-base md:text-lg text-on-surface-variant mb-10 leading-relaxed">{item.body}</p><Link href={item.href} className="inline-flex items-center h-[52px] px-8 bg-primary-container text-on-primary-container font-manrope text-xs uppercase tracking-widest border border-primary-container hover:bg-primary hover:text-on-primary transition-colors">{item.button}</Link></div></div></section>)}</main>
}
