-- Generated/documented for Supabase PostgreSQL. The Express API is the only runtime database client.
create table if not exists public.admin_settings (
  key text primary key,
  value text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  main_category text not null check (main_category in ('bags', 'jewelry', 'accessories', 'home')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text not null default '',
  description text not null default '',
  price numeric(12,2) not null check (price >= 0),
  main_category text not null check (main_category in ('bags', 'jewelry', 'accessories', 'home')),
  category text not null default '',
  status text not null default 'available' check (status in ('available', 'reserved', 'sold')),
  badge text check (badge in ('New', 'Limited')),
  quantity integer not null default 1 check (quantity >= 0),
  images jsonb not null default '[]'::jsonb,
  bg_class text not null default 'bg-surface-container',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();
drop trigger if exists store_settings_set_updated_at on public.store_settings;
create trigger store_settings_set_updated_at before update on public.store_settings for each row execute function public.set_updated_at();

alter table public.admin_settings enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.store_settings enable row level security;
-- The service-role key used exclusively by Express bypasses RLS. Do not add browser policies.

insert into storage.buckets (id, name, public) values ('product-images', 'product-images', true) on conflict (id) do nothing;
